// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using GeoToolkit;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace GeoToolkitTest
{
	/// <summary>
	///This is a test class for GeoToolkit.UrlBuilder and is intended
	///to contain all GeoToolkit.UrlBuilder Unit Tests
	///</summary>
	[TestClass]
	public class UrlBuilderTest
	{
		private TestContext testContextInstance;

		/// <summary>
		///Gets or sets the test context which provides
		///information about and functionality for the current test run.
		///</summary>
		public TestContext TestContext
		{
			get { return testContextInstance; }
			set { testContextInstance = value; }
		}

		#region Additional test attributes

		// 
		//You can use the following additional attributes as you write your tests:
		//
		//Use ClassInitialize to run code before running the first test in the class
		//
		//[ClassInitialize()]
		//public static void MyClassInitialize(TestContext testContext)
		//{
		//}
		//
		//Use ClassCleanup to run code after all tests in a class have run
		//
		//[ClassCleanup()]
		//public static void MyClassCleanup()
		//{
		//}
		//
		//Use TestInitialize to run code before running each test
		//
		//[TestInitialize()]
		//public void MyTestInitialize()
		//{
		//}
		//
		//Use TestCleanup to run code after each test has run
		//
		//[TestCleanup()]
		//public void MyTestCleanup()
		//{
		//}
		//

		#endregion

		/// <summary>
		///A test for ToString ()
		///</summary>
		[TestMethod]
		public void UrlBuilder()
		{
			UrlBuilder target = new UrlBuilder(@"http://somesite.com/somefolder/somepage.aspx?param1=aaa&param2=bbb");

			Assert.AreEqual(target["param1"], "aaa");
			Assert.IsNull(target["param3"]);

			target["param1"] = "ccc";
			Assert.AreEqual(@"http://somesite.com/somefolder/somepage.aspx?param1=ccc&param2=bbb", target.ToString());

			target["param1"] = null;
			Assert.AreEqual(@"http://somesite.com/somefolder/somepage.aspx?param2=bbb", target.ToString());

			target["param2"] = null;
			Assert.AreEqual(@"http://somesite.com/somefolder/somepage.aspx", target.ToString());

			target["param3"] = "ddd";
			Assert.AreEqual(@"http://somesite.com/somefolder/somepage.aspx?param3=ddd", target.ToString());
		}
	}
}